In [4]:
## BASIC PYTON SESI 1

angka_1 = 5
kalimat_1 = "Hello World"
# var3 = input("Masukkan Angka: ")
angka_2 = 10

# cara normal
print("Hasil :" , angka_1)

# lebih enak jika pakai f (supaya bisa pake {variable})
print(f"Hasil : {angka_1}")
# contoh arithmetic
# + - * / semuanya caranya sama 
print("====== + - / * ======")
print(angka_1 + angka_2)
print(angka_1 - angka_2)
print(angka_1 / angka_2)
print(angka_1 * angka_2)

# **
print("====== ** ======")
print(3**4)

# //
print("====== // ======")
# habis dibagi lalu dibuletin kebawah
print(32//7)

# selection (if else)
print("====== if else ======")

angka_1 = 5
if(angka_1 < 10) : 
    print("angka 1 lebih kecil daripada 10")
elif(angka_1 == 10 and 10 == 10) :
    print("angka 1 sama dengan 10")
else :
    print("angka 1 lebih dari 10")

# looping
print("====== looping ======")
for i in range(5):
    print(i)

angka_1 = 1
while(angka_1 < 5):
    print(angka_1)
    angka_1 += 1
    
# function
print("====== function ======")
def tambah(x, y, z = 10):
    print(f"{x + y} : default z : {z}")
    
tambah(5, 10)

Hasil : 5
Hasil : 5
====== + - / * ======
15
-5
0.5
50
====== ** ======
81
====== // ======
4
====== if else ======
angka 1 lebih kecil daripada 10
====== looping ======
0
1
2
3
4
1
2
3
4
====== function ======
15 : default z : 10


In [1]:
# LIST []
 # Changeable, Ordered, Indexed
# DICTIONARY {}
 # Changeable, Unordered, Indexed
# TUPLE
 # Unchangeable, Ordered, Indexed
# SET
 # Unordered


# list
list_hewan = ["anjing", "kucing", "marco"]
print(list_hewan)
print(list_hewan[0])

# dictionary 
# mirip json
# key : value
orang_1 = {"nama" : "kolin", "umur" : 12}

print(orang_1)
# cara akses ke dalam
print(orang_1["nama"])

# Set
set = {"set1", "set2", "set3", "set1"}
print(set)


# Tuple
tuple = ("tuple1", "tuple2", "tuple3")
print(tuple) 

# pakai :
print(list_hewan[:2]) # berarti print sampai index ke 2
print(list_hewan[2:]) # berarti print dari index 2 dan seterusnya

['anjing', 'kucing', 'marco']
anjing
{'nama': 'kolin', 'umur': 12}
kolin
{'set3', 'set2', 'set1'}
('tuple1', 'tuple2', 'tuple3')
['anjing', 'kucing']
['marco']


In [3]:
dictionary = {"name": "kolin", "age" : 9}
# 'title' : 'value'

print(dictionary["name"])

dictionary_with_list = [
    {
        "name" : "kolin",
        "age" : 2
    },
    {
        "name" : "kepin",
        "age" : 10
    }
]

print(dictionary_with_list[0]["name"])

for person in dictionary_with_list :
    print(f"name : {person['name']}")

tuple = (1,3,4)

print(tuple[2])

set = {10,2,3}
set2 = {10,1,5}

hasil = set.intersection(set2)

print(hasil)

name = input("Enter your name: ")
print(f"Hello, {name}!")


kolin
kolin
name : kolin
name : kepin
4
{10}
Hello, ashid!


In [2]:
import numpy as np  

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(f"ndim : {arr.ndim}")
print(f"shape : {arr.shape}")

zeros = np.zeros((2,3))
print(zeros)

ones = np.ones((2,2))
print(ones)

empty = np.empty((2,3))
print(empty)

random = np.random.random((2,3))
print(random)

arr = [1,2,3,4]
result_sum = np.sum(arr)

print('\n')
numbers = [1,2,3,4,5,6,7]
print(numbers[::2])



ndim : 2
shape : (2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.84715337 0.60646299 0.73287858]
 [0.40876557 0.87356435 0.06594394]]


[1, 3, 5, 7]


In [16]:
name = input("input your name : ")

if name == "kolin":
    print("namanya kolin")
elif name == "stiphen" :
    print("namanya stiphen")
else : 
    print("bukan siapa siapa")
    
    
for i in range(10) :
	print(i)
 
for i in range(1, 7, 2) : 
	print(i)

bukan siapa siapa
0
1
2
3
4
5
6
7
8
9
1
3
5


SyntaxError: invalid syntax (409182370.py, line 3)