In [8]:
import numpy as np

list = [1,2,3]
list2 = [
    [1,2,3],
    [4,5,6]
]

# buat menjadi numpy array supaya arraynya bisa digabungin dengan numpy yang lain
array = np.array(list)
array2 = np.array(list2)
print(array)
print(array2)

print(array.shape) 
# outputnya (3,) ada 3 isi dan 1 row
# yaitu berarti cuman ada 
print(array2.shape)
# outputnya bakalan (2,3) ada 3 isi dan 2 row

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)


In [9]:
list = [
    [-1,2,3],
    [4,-5,6],
    [7,8,9] 
]

# guna numpy abs adalah supaya isinya menjadi absolute (tidak minus)
# intinya membuat semuanya menjadii positive
print(np.abs(list))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
