In [9]:
import numpy as np  

x = [
    [9,2,3],
    [4,11,3],
    [2,-3,6]
]

y = [
    12,9,6
]

def gaussian(x,y, iteration = 20, tolerance = 0.052):
    diagonal = np.diag(np.array(x))
    # np.diag sini berguna untuk mengambil garis diagonal dalam suatu array
    # x1 y1 z1
    # x2 y2 z2
    # x3 y3 z3
    # dengan np.diag berarti nanti hasil yang didapatkan bakalan menjadi x1, y2, z3
    
    np.fill_diagonal(x, 0)
    # fill_diagonal sama seperti np.diag tapi versi assign
    # disebelah x ada 0, yaitu yang mau di assign
    
    # x1 y1 z1
    # x2 y2 z2
    # x3 y3 z3
    
    # menjadi 
    
    # 0 y1 z1
    # x2 0 z2
    # x3 y3 0
    
    sum = np.sum(np.abs(x), axis = 1)
    # np.sum gunanya untuk menjumlahkan kolumn / baris di index pada suatu array
    # nah karena mau dijumlahin makanya harus di np.abs yaitu membuat semuanya jadi positif
    # axis = 1 -> penjumlahan untuk baris
    # axis = 0 -> penjumlahan untuk kolum
    
    print(sum)  
    if not np.all(np.abs(diagonal) > sum):
        print("Not diagonally dominant")
        return False
    
    x = -x 
    saver = np.zeros(np.size(x[0]))
    # np.zeros berguna untuk assign value ke 0
    # np.size sama seperti size pada biasanya [1,2,3] -> sizenya 3
    
    for i in range(iteration) :
        answer = np.array(saver)

        for index, value in enumerate(x):
            # enumerate -> supaya bisa ambil return yang baru yaitu value 
            answer[index] = (y[index] + np.dot(answer, value))/diagonal[index] # rumus gauss seidel
            # np.dot sama seperti dot product
            
            # [x1,y1,z1]
            # [x2,y2,z2]
            
            # (x1 * x2) + (y1 * y2) + (z1 * z2)
            
        print(i ,'iteration : ', answer)
        
        distance = np.sqrt(np.dot(answer - saver, answer - saver))
        # distancenya pakai rumus euclidian distance (phytagoras)
        # rumusnya : akar((x1 - x2)^2 - (y1 - y2)^ 2)
        # np.sqrt -> akar
        
        # kenapa answer - saver 2x di np.dot ?
        # jika kita lihat di rumusnya ada (x1 - x2)^2 
        # nah anggap answer - saver ini sebagai x1 - x2
        # nah yang keduanya juga sama, tapi karena kita pakai np.dot
        # jadinya bakalan dikali dan karena sama valuenya -> jatohnya jadi pangkat 2
        
        if(distance < tolerance) :
            return answer
        saver = np.array(answer)
        # simpan untuk next iterasi
    
gaussian(x,y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
